version: '3.3'

services:
  php:
    container_name: php
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: './php'
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
        - PECL_XDEBUG_INSTALL_SUFFIX
        - PECL_MONGODB_INSTALL_SUFFIX
        - COMPOSER_VERSION
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      - ./app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    depends_on:
      - yii-mysql

  yii-mysql:
    container_name: yii-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'yii2'
      MYSQL_USER: 'yii2-user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","uroot","-proot", "|" ,"grep","alive"]
      timeout: 20s
      retries: 10
    volumes:
      - ${MOUNT_FOLDER}/mysql/yii/data:/var/lib/mysql
